---
title: "Curriculum Vitae"
editor: visual
---

## Contact Information

{{< fa envelope >}} [ostephen@mun.ca](mailto:ostephen@mun.ca)

{{< fa phone >}} (709) 631-4033

{{< fa paper-plane >}} Department of Economics

     Memorial University of Newfoundland

     100 Elizabeth Avenue

     St John's , NL, Canada

     A1C 5S7


## Education

-   M.A. Economics (2024), Memorial University of Newfoundland

-   B.Sc. Economics (2013), University of Ilorin

## Skills

-   Excellent Customer service

-   Presentation skills

-   Microsoft Office

-   Detail-oriented and prudent in the performance of duties

-   Good Teamwork

-   Excellent communication skills and interpersonal skills

-   Excellent interpersonal relationship skills

-   Strong sense of responsibility and commitment to assigned targets and tasks

-   Organization and Planning skills


## Work experience 

-   General Assistant
The Berkeley Scott Agency - London
June 2022 to August 2022

-   Administrator
Kim s food - London
April 2022 to April 2022

-   Teacher
Government of Nigeria - Ilorin
December 2016 to August 2020

-   ECONOMIST and PAYROLL AUDITOR
State of Osun Integrated Payroll and Personnel Management System (IPPMS). - Osogbo
January 2015 to November 2016

-   Chamber Administrator
Bolarinwa &Co. Legal firm - Osogbo, Osun State.
October 2014 to December 2014

## Volunteer Experience

-   Volunteer Customer Service
Habitat for Humanity – St. John’s, NL
October 2022 to present.

-   Volunteer Project Administrator
SAFYI (Science Advocacy for Youngsters initiative) - Osogbo
September 2020 to March 2022

## Languages

-   English

-   French: Beginner

-   Yoruba